photo_mas=[
    {
        'data_aos':0,
        'img':"img_4.jpg"
    },
    {
        'data_aos':100,
        'img':"img_5.jpg"
    },
    {
        'data_aos':200,
        'img':"img_1.jpg"
    },

    {
        'data_aos':0,
        'img':"img_2.jpg"
    },
    {
        'data_aos':100,
        'img':"img_3.jpg"
    },
    {
        'data_aos':200,
        'img':"img_6.jpg"
    },
    {
        'data_aos':0,
        'img':"img_7.jpg"
    },
    {
        'data_aos':100,
        'img':"img_8.jpg"
    },
    {
        'data_aos':200,
        'img':"img_9.jpg"
    },
    {
        'data_aos':0,
        'img':"img_10.jpg"
    },
    {
        'data_aos':100,
        'img':"img_1.jpg"
    },
    {
        'data_aos':200,
        'img':"img_2.jpg"
    },
    {
        'data_aos':0,
        'img':"img_3.jpg"
    },
    {
        'data_aos':100,
        'img':"img_4.jpg"
    },
    {
        'data_aos':200,
        'img':"img_5.jpg"
    },
    {
        'data_aos':0,
        'img':"img_6.jpg"
    },
    {
        'data_aos':100,
        'img':"img_7.jpg"
    },
    {
        'data_aos':200,
        'img':"img_8.jpg"
    },
    {
        'data_aos':100,
        'img':"img_9.jpg"
    },
    {
        'data_aos':100,
        'img':"img_4.jpg"
    },
    {
        'data_aos':200,
        'img':"img_5.jpg"
    },
]